name: CI / CD for Angular
on:
  push:
    branches:
       - dev
  pull_request:
          branches:
            - dev
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build -- --configuration production --base-href "/jenkins-angular/"
        
  steps:
    runs-on:
        - uses: actions/checkout@v3
        - name: All things angular
          uses: AhsanAyaz/angular-deploy-gh-pages-actions@[version] ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
          with:
            github_access_token: ${{ secrets.TOKEN }} # see the Configuration section for how you can create secrets
            build_configuration: staging # The build environment for the app. please look configurations in your angular.json
            base_href: /jenkins-angular/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
            deploy_branch: deploy # The branch the action should deploy to.
            angular_dist_build_folder: dist/my-app # The folder where your project is supposed to be after running ng build by the action.

permissions:
    contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
